# Generated by Django 4.0.1 on 2022-01-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver_app', '0002_alter_data_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
