# Generated by Django 4.0.1 on 2022-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver_app', '0003_alter_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
